### ISSUE TITLE
Release on crates.io

### ISSUE THREAD

**Issue by KodrAus** [budziq/pulls_since#1]
It would be great to release this on crates.io so we could just `cargo install pulls_since` and then start querying repos.

**Comment by budziq** [comment]
I'll try to find some time to do it later today :+1:

**Comment by budziq** [comment]
@KodrAus done :smile: => [![crates.io](https://img.shields.io/crates/v/pulls_since.svg)](https://crates.io/crates/pulls_since)

**Comment by KodrAus** [comment]
`\o/`
