### ISSUE TITLE
Support querying a whole organization

### ISSUE THREAD

**Issue by jdm** [budziq/pulls_since#12]
Rather than specifying individual repositories, it would be nice to be able to see all of the pull requests closed in any repository owned by an organization.

**Comment by budziq** [comment]
Thanks!

Not sure when I'll get to doing it but it should be trivial with
`https://api.github.com/orgs/rust-lang-nursery/repos` - for orgs
`https://api.github.com/users/budziq/repos` - for users

both return list of dicts with "full_name" key in the form "owner/repo"

**Comment by KodrAus** [comment]
Could it be worth looking at something like [`github-rs`](https://github.com/mgattozzi/github-rs) if the sources for contributions are going to get more substantial?

**Comment by budziq** [comment]
Hi! Getting all pulls from github organization or github user is available in version 0.4.0 I've just released to crates.io.
